"use client";

/**
 * AmplifyProvider — configures the Amplify client for browser use.
 *
 * Wraps <body> contents in app/layout.tsx. The `{ ssr: true }` flag enables
 * cookie-based auth for the server-side Amplify adapter used in
 * lib/amplify-server-utils.ts.
 *
 * amplify_outputs.json is generated by:
 *   - Local dev:  npx ampx sandbox
 *   - CI/CD:      npx ampx generate outputs  (runs before next build in amplify.yml)
 */

import { Amplify } from "aws-amplify";
import outputs from "../../../amplify_outputs.json";

Amplify.configure(outputs, { ssr: true });

export function AmplifyProvider({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
